# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Feature')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Hashtag')),
            ],
        ),
        migrations.AddField(
            model_name='hashtag',
            name='features',
            field=models.ManyToManyField(through='cv.Link', to='cv.Feature'),
        ),
    ]
