# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion 

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# cv.migrations.0003_auto_20151227_1224

def create_notset_employer(apps, schema_editor):
    Employer = apps.get_model("cv.Employer")
    notset = Employer(id="notset", name="Not set", website="http://127.0.0.1")
    notset.save()

class Migration(migrations.Migration):

    replaces = [('cv', '0002_auto_20151227_1223'), ('cv', '0003_auto_20151227_1306'), ('cv', '0003_auto_20151227_1224'), ('cv', '0004_feature_employer'), ('cv', '0005_auto_20151228_1131')]

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField()),
                ('logo', models.ImageField(blank=True, upload_to='/cv/logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(blank=True, max_length=254)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv.Recommendation'),
        ),
        migrations.RunPython(
            code=create_notset_employer
        ),
        migrations.AddField(
            model_name='feature',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cv.Employer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, upload_to='cv/logos/'),
        ),
    ]
